version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./packages/nginx/common:/usr/share/nginx/html/common
    ports:
      - 8080:3000
    depends_on:
      - team_catalog
      - team_marketing
      - team_sales
      - team_orchestrator

  team_orchestrator:
    build: ./packages/team-orchestrator
    ports:
      - "3001:3001"
    volumes:
      - ./packages/team-orchestrator:/code

  team_catalog:
    build: ./packages/team-catalog
    ports:
      - "3002:3002"
    volumes:
      - ./packages/team-catalog:/code

  team_sales:
    build: ./packages/team-sales
    ports:
      - "3003:3003"
    volumes:
      - ./packages/team-sales:/code
      
  team_marketing:
    build: ./packages/team-marketing
    ports:
      - "3004:3004"
    volumes:
      - ./packages/team-marketing:/code